### ISSUE TITLE
Handling simultaneous access while database modification

### ISSUE THREAD

**Issue by suvayu** [domo141/nottoomuch#2]
Not sure if this can really be done any better.  I was doing a rebuild of the database, when a cron job ran offlineimap and notmuch new.  This made the database rebuild fail prematurely like this:

```
$ ./nottoomuch-addresses.sh --update --rebuild
Creating '/home/user/.config/nottoomuch/addresses'. This may take some time...
terminate called after throwing an instance of 'Xapian::DatabaseModifiedError'
Added 6786 active addresses in 139 seconds.
Total number of active addresses: 6786.
```

**Comment by domo141** [comment]
Now, version 2.5 of nottoomuch-addresses.sh (well, 2.4 already) uses that temporary file so database
is locked for shorter period of time.

Ultimately, the locking of db could be made shorter by dumping all output to a file, and after notmuch search
has exited, start filtering ignores out. 

Since --update / --rebuild is supposed to be done manually (and not too often), and, if there is chance for
(unrecoverable) database failure anyway, to improve things further, change to notmuch (i.e. retry in case of
such a known potential failurre) should be done instead (if not already done!)

closing as, IMO, solution good enough.
